version: "3"
services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    # environment:
    #   - SE_VNC_NO_PASSWORD=1 # NO_PASSWORD
    #   - SE_VNC_VIEW_ONLY=1   # readonly



  # docker run --rm -it -p 4444:4444 -p 7900:7900 --shm-size 2g selenium/standalone-chrome
