services:
  - type: web
    name: chrome
    runtime: docker
    image: selenium/standalone-chrome
    ports:
      - port: 4444
        protocol: TCP
        external: true
      - port: 7900
        protocol: TCP
        external: true
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_VNC_VIEW_ONLY=1
