services:
  - type: web
    name: chrome
    runtime: image
    image:
      url: docker.io/selenium/standalone-chrome:latest
    envVars:
      - key: RENDER_SERVICE_PORT
        value: 4444
      - key: PORT
        value: 4444
      - key: SE_VNC_NO_PASSWORD
        value: 1
      - key: SE_VNC_VIEW_ONLY
        value: 1
      



# render.yaml

services: 
  type: pserv 
  name: selenium-standalone-chrome-debug 
  env: docker 
  dockerfilePath: ./Dockerfile.selenium
